name: CI
on:
  push:
    branches: [ master ]
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Get current timestamp
        id: time
        run: echo "::set-output name=time::$(date +'%F')"
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0
        
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.6.1
        with:
          push: true
          tags: |
            ghcr.io/lucaelin/nextcloud-news-updater:${{ steps.time.outputs.time }}
            ghcr.io/lucaelin/nextcloud-news-updater:latest
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
